### PR TITLE
Feature/74761 video text transcript

### PR DESCRIPTION
**Pull request by sushmi21**
This PR adds a download button for downloading video transcripts when available

- Check if clicking the 'Download transcript' button downloads a text file with transcripts
- Check if the button receives focus during keyboard navigation
- Check if the button receives visible keyboard focus
- Check if the button is not displayed when there is no alt text for video

### CODE REVIEW

**Comment by sushmi21** [comment]
Please review https://github.com/Cognigy/chat-components/pull/82 before this PR

**Review by kwinto — APPROVED** [review]
In the future, we may want to implement real subtitle capabilities. Current implementation should be sufficient for the certification.

https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video

**Comment by sushmi21** [comment]
> In the future, we may want to implement real subtitle capabilities. Current implementation should be sufficient for the certification.
> 
> https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video

For a video (with audio) to be accessible, it should have both captions and a transcript. Captions are essential for those who are deaf or have hearing issues. Transcripts are for people who are blind. For video-only content, transcript is enough.

**Comment by sushmi21** [comment]
> In the future, we may want to implement real subtitle capabilities. Current implementation should be sufficient for the certification.
> 
> https://developer.mozilla.org/en-US/docs/Web/Media/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video

Thanks for the link. It will be helpful for one of the next tickets that I will work on

**Pull request merged**
