### PR TITLE
Disabled QR

### PR DESCRIPTION
**Pull request by kwinto**
This PR reworks logic for the QR Buttons being disabled. Now, this status is dependent on presence of user message after the message with QR.

Please test alongside with the PR in WebchatWidget repo.
https://github.com/Cognigy/WebchatWidget/pull/350

### CODE REVIEW

**Comment by fabclj** [comment]
@kwinto should not be better to add disable property to the disabled buttons?

**Comment by fabclj** [comment]
@kwinto during my test using the provided endpoint, the PR1 and PR2 are blocked, but PR Phone Number still triggers the action

**Comment by kwinto** [comment]
> @kwinto should not be better to add disable property to the disabled buttons?

It's already done like that. On the upper level though, it's handled by "undefined" action property, as this would be the simplest case to handle for:
- Insights
- Read-only chat
- etc

**Comment by fabclj** [comment]
In this case last message buttons PR1 and PR2 are active but are not triggering any action. Is it expected?

Screenshot from 2023-12-12 12-02-27

**Comment by kwinto** [comment]
> In this case last message buttons QR1 and QR2 are active but are not triggering any action. Is it expected?
> 
> Screenshot from 2023-12-12 12-02-27

Yes, at least it is the same behaviour on the Webchat v2 branch. I have not provided any "postback" value for those buttons.

**Review by fabclj — APPROVED** [review]

**Pull request merged**
